### ISSUE TITLE
ChatGPT Hard-Fork

### ISSUE THREAD

**Issue by mikesoylu** [aduros/ai.vim#17]
Hey there love this plugin 🔥  

I've spun off a hard-fork [here](https://github.com/mikesoylu/ai.vim) that is based on ChatGPT and removes some functionality that you have here (diverges quite a bit from this main)

Changes introduced:

- Streaming completions with cancelling
- ChatGPT-only calls for completions & edits
- Removed some settings and loading state indicators that are no longer needed

Let me know if you'd like me to open a PR to merge those changes in 🙌

**Comment by aduros** [comment]
Hi, sounds promising! I'll play around with your fork this weekend.

How does the streaming work? It actually updates the buffer in realtime?

**Comment by mikesoylu** [comment]
Cool 🙌 Streaming uses the `--no-buffer` option of curl together with the api’s `stream: true` option and inserts every new token into the buffer as they’re available.

**Comment by aduros** [comment]
I had a go with it over the weekend, awesome work!! The streaming really makes it feel more responsive!

I like the idea of using the Chat API, since it's faster and cheaper, but the results are worse than the regular completions/edits APIs. It seems like Chat has issues where it ignores the prompt and reverts to being a virtual assistant. I think they intend to fix that in a future model though, so let's keep an eye on it... At the pace that things are going this could be an option in a month or two.
